"""add inventory sold_units and whatsapp messages

Revision ID: 9bdbc9bc3824
Revises: f8ac24fba947
Create Date: 2026-08-30 17:58:57.467648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bdbc9bc3824'
down_revision = 'f8ac24fba947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('phone_number', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('provider_response', sa.JSON(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('whatsapp_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whatsapp_messages_customer_id'), ['customer_id'], unique=False)

    with op.batch_alter_table('inventory_financing_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sold_units', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))

    with op.batch_alter_table('inventory_financing_items', schema=None) as batch_op:
        batch_op.alter_column('sold_units', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_financing_items', schema=None) as batch_op:
        batch_op.drop_column('sold_units')

    with op.batch_alter_table('whatsapp_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatsapp_messages_customer_id'))

    op.drop_table('whatsapp_messages')
    # ### end Alembic commands ###
