"""add auth, encryption, and feature tables

Revision ID: ca3837b1887f
Revises: 8141b9676fdb
Create Date: 2026-08-29 18:00:19.532469

IMPORTANT - this migration changes customers.phone_number, national_id, email,
kra_pin, next_of_kin_phone, and address from plaintext to Fernet-encrypted
storage (app.security.EncryptedString), and adds a blind-index hash column
next to each searchable field (phone_number_hash, national_id_hash,
email_hash) so uniqueness checks and exact-match lookups keep working without
ever comparing ciphertext directly (see app.security.blind_index).

Because encryption/decryption happens in the ORM layer (TypeDecorator), not
in the database, simply changing the column type here would NOT encrypt
existing rows - on the next read, the app would try to Fernet-decrypt
already-plaintext data, fail, and silently return None (see
EncryptedString.process_result_value), which reads as silent data loss.
Steps 2-3 below exist specifically to prevent that: every existing row is
re-encrypted and hashed in place before the NOT NULL/unique constraints are
applied. FIELD_ENCRYPTION_KEY must be set in the environment before running
`flask db upgrade` for this revision.
"""
import hashlib
import hmac
import os

from alembic import op
import sqlalchemy as sa
from cryptography.fernet import Fernet

import app.security


# revision identifiers, used by Alembic.
revision = 'ca3837b1887f'
down_revision = '8141b9676fdb'
branch_labels = None
depends_on = None


def _fernet():
    key = os.environ.get('FIELD_ENCRYPTION_KEY')
    if not key:
        raise RuntimeError(
            'FIELD_ENCRYPTION_KEY must be set to run this migration (it re-encrypts '
            'existing customer PII). Generate one with: '
            'python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"'
        )
    return Fernet(key.encode('utf-8'))


def _blind_index(value):
    if value is None:
        return None
    pepper = os.environ['FIELD_ENCRYPTION_KEY'].encode('utf-8')
    normalized = str(value).strip().lower()
    return hmac.new(pepper, normalized.encode('utf-8'), hashlib.sha256).hexdigest()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_targets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('market', sa.String(length=160), nullable=True),
    sa.Column('set_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collection_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_targets_period_start'), ['period_start'], unique=False)

    op.create_table('lending_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('market', sa.String(length=160), nullable=True),
    sa.Column('shared_liability', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('airtel_money_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('loan_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('phone_number', sa.String(length=16), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('airtel_money_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('callback_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    with op.batch_alter_table('airtel_money_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_airtel_money_requests_loan_id'), ['loan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_airtel_money_requests_status'), ['status'], unique=False)

    op.create_table('external_lookups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('request_reference', sa.String(length=100), nullable=True),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.Column('requested_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('external_lookups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_lookups_customer_id'), ['customer_id'], unique=False)

    op.create_table('inventory_financing_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('loan_id', sa.String(length=36), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('supplier', sa.String(length=160), nullable=True),
    sa.Column('purchased_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_financing_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_financing_items_loan_id'), ['loan_id'], unique=False)

    op.create_table('risk_alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('loan_id', sa.String(length=36), nullable=True),
    sa.Column('alert_type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_alerts_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_alerts_loan_id'), ['loan_id'], unique=False)

    op.create_table('stripe_payment_intents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('loan_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('payment_intent_id', sa.String(length=100), nullable=False),
    sa.Column('client_secret', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_intent_id')
    )
    with op.batch_alter_table('stripe_payment_intents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stripe_payment_intents_loan_id'), ['loan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stripe_payment_intents_status'), ['status'], unique=False)

    op.create_table('payment_reminders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('loan_id', sa.String(length=36), nullable=False),
    sa.Column('schedule_item_id', sa.String(length=36), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('recipient_phone', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('provider_response', sa.JSON(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['schedule_item_id'], ['repayment_schedule_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_reminders_loan_id'), ['loan_id'], unique=False)

    # ---- Step 1: add the new customer columns WITHOUT constraints yet -------
    # hash columns start nullable and non-unique so the backfill in step 2 can
    # populate them row by row before we lock the schema down in step 3.
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('national_id_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('email_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('group_id', sa.String(length=36), nullable=True))
        # Widen the plaintext columns first so encrypted values (which run
        # longer than plaintext) fit once step 2 overwrites them - still plain
        # VARCHAR at this point, not yet EncryptedString, so plaintext already
        # in these columns stays readable for the backfill below.
        batch_op.alter_column('phone_number', existing_type=sa.VARCHAR(length=16), type_=sa.String(length=255), existing_nullable=False)
        batch_op.alter_column('national_id', existing_type=sa.VARCHAR(length=32), type_=sa.String(length=255), existing_nullable=False)
        batch_op.alter_column('kra_pin', existing_type=sa.VARCHAR(length=32), type_=sa.String(length=255), existing_nullable=True)
        batch_op.alter_column('next_of_kin_phone', existing_type=sa.VARCHAR(length=16), type_=sa.String(length=255), existing_nullable=True)
        batch_op.alter_column('email', existing_type=sa.VARCHAR(length=120), type_=sa.String(length=255), existing_nullable=True)
        batch_op.alter_column('address', existing_type=sa.TEXT(), type_=sa.String(length=1000), existing_nullable=True)

    # ---- Step 2: re-encrypt every existing row in place and backfill hashes --
    connection = op.get_bind()
    customers_table = sa.table(
        'customers', sa.column('id', sa.String), sa.column('phone_number', sa.String),
        sa.column('national_id', sa.String), sa.column('kra_pin', sa.String),
        sa.column('next_of_kin_phone', sa.String), sa.column('email', sa.String),
        sa.column('address', sa.String), sa.column('phone_number_hash', sa.String),
        sa.column('national_id_hash', sa.String), sa.column('email_hash', sa.String),
    )
    fernet = _fernet()
    rows = connection.execute(sa.select(
        customers_table.c.id, customers_table.c.phone_number, customers_table.c.national_id,
        customers_table.c.kra_pin, customers_table.c.next_of_kin_phone, customers_table.c.email,
        customers_table.c.address,
    )).fetchall()

    def encrypt(value):
        return fernet.encrypt(str(value).encode('utf-8')).decode('utf-8') if value is not None else None

    for row in rows:
        connection.execute(
            customers_table.update().where(customers_table.c.id == row.id).values(
                phone_number=encrypt(row.phone_number),
                national_id=encrypt(row.national_id),
                kra_pin=encrypt(row.kra_pin),
                next_of_kin_phone=encrypt(row.next_of_kin_phone),
                email=encrypt(row.email),
                address=encrypt(row.address),
                phone_number_hash=_blind_index(row.phone_number),
                national_id_hash=_blind_index(row.national_id),
                email_hash=_blind_index(row.email),
            )
        )

    # ---- Step 3: now that every row has a hash, lock the schema down --------
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('phone_number_hash', existing_type=sa.String(length=64), nullable=False)
        batch_op.alter_column('national_id_hash', existing_type=sa.String(length=64), nullable=False)
        batch_op.alter_column('phone_number', existing_type=sa.String(length=255), type_=app.security.EncryptedString(length=255), existing_nullable=False)
        batch_op.alter_column('national_id', existing_type=sa.String(length=255), type_=app.security.EncryptedString(length=255), existing_nullable=False)
        batch_op.alter_column('kra_pin', existing_type=sa.String(length=255), type_=app.security.EncryptedString(length=255), existing_nullable=True)
        batch_op.alter_column('next_of_kin_phone', existing_type=sa.String(length=255), type_=app.security.EncryptedString(length=255), existing_nullable=True)
        batch_op.alter_column('email', existing_type=sa.String(length=255), type_=app.security.EncryptedString(length=255), existing_nullable=True)
        batch_op.alter_column('address', existing_type=sa.String(length=1000), type_=app.security.EncryptedString(length=1000), existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_customers_email_hash'), ['email_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_customers_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_national_id_hash'), ['national_id_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_customers_phone_number_hash'), ['phone_number_hash'], unique=True)
        batch_op.create_foreign_key('fk_customers_group_id_lending_groups', 'lending_groups', ['group_id'], ['id'])

    with op.batch_alter_table('disbursements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disbursed_by_user_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_disbursements_disbursed_by_user_id_users', 'users', ['disbursed_by_user_id'], ['id'])

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_loans_group_id'), ['group_id'], unique=False)
        batch_op.create_foreign_key('fk_loans_group_id_lending_groups', 'lending_groups', ['group_id'], ['id'])

    with op.batch_alter_table('repayment_schedule_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_due_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('rescheduled_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('reschedule_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_reminder_sent_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('repayments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recorded_by_user_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_repayments_recorded_by_user_id_users', 'users', ['recorded_by_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # Note: downgrading discards encryption - phone/national ID/email revert to
    # plain VARCHAR but keep their last encrypted ciphertext as inert text
    # (not re-decrypted), since a reliable reverse-migration would need the
    # same FIELD_ENCRYPTION_KEY that encrypted them, which may have rotated by
    # the time anyone downgrades. Treat this as a schema-only rollback for a
    # dev/staging database, not a safe production downgrade path.
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repayments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_repayments_recorded_by_user_id_users', type_='foreignkey')
        batch_op.drop_column('recorded_by_user_id')

    with op.batch_alter_table('repayment_schedule_items', schema=None) as batch_op:
        batch_op.drop_column('last_reminder_sent_at')
        batch_op.drop_column('reschedule_reason')
        batch_op.drop_column('rescheduled_count')
        batch_op.drop_column('original_due_date')

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_constraint('fk_loans_group_id_lending_groups', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_loans_group_id'))
        batch_op.drop_column('group_id')

    with op.batch_alter_table('disbursements', schema=None) as batch_op:
        batch_op.drop_constraint('fk_disbursements_disbursed_by_user_id_users', type_='foreignkey')
        batch_op.drop_column('disbursed_by_user_id')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_customers_group_id_lending_groups', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_customers_phone_number_hash'))
        batch_op.drop_index(batch_op.f('ix_customers_national_id_hash'))
        batch_op.drop_index(batch_op.f('ix_customers_group_id'))
        batch_op.drop_index(batch_op.f('ix_customers_email_hash'))
        batch_op.alter_column('address', existing_type=app.security.EncryptedString(length=1000), type_=sa.TEXT(), existing_nullable=True)
        batch_op.alter_column('email', existing_type=app.security.EncryptedString(length=255), type_=sa.VARCHAR(length=120), existing_nullable=True)
        batch_op.alter_column('next_of_kin_phone', existing_type=app.security.EncryptedString(length=255), type_=sa.VARCHAR(length=16), existing_nullable=True)
        batch_op.alter_column('kra_pin', existing_type=app.security.EncryptedString(length=255), type_=sa.VARCHAR(length=32), existing_nullable=True)
        batch_op.alter_column('national_id', existing_type=app.security.EncryptedString(length=255), type_=sa.VARCHAR(length=32), existing_nullable=False)
        batch_op.alter_column('phone_number', existing_type=app.security.EncryptedString(length=255), type_=sa.VARCHAR(length=16), existing_nullable=False)
        batch_op.drop_column('group_id')
        batch_op.drop_column('email_hash')
        batch_op.drop_column('national_id_hash')
        batch_op.drop_column('phone_number_hash')

    with op.batch_alter_table('payment_reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_reminders_loan_id'))

    op.drop_table('payment_reminders')
    with op.batch_alter_table('stripe_payment_intents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stripe_payment_intents_status'))
        batch_op.drop_index(batch_op.f('ix_stripe_payment_intents_loan_id'))

    op.drop_table('stripe_payment_intents')
    with op.batch_alter_table('risk_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_alerts_loan_id'))
        batch_op.drop_index(batch_op.f('ix_risk_alerts_customer_id'))
        batch_op.drop_index(batch_op.f('ix_risk_alerts_created_at'))

    op.drop_table('risk_alerts')
    with op.batch_alter_table('inventory_financing_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_financing_items_loan_id'))

    op.drop_table('inventory_financing_items')
    with op.batch_alter_table('external_lookups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_lookups_customer_id'))

    op.drop_table('external_lookups')
    with op.batch_alter_table('airtel_money_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_airtel_money_requests_status'))
        batch_op.drop_index(batch_op.f('ix_airtel_money_requests_loan_id'))

    op.drop_table('airtel_money_requests')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    op.drop_table('lending_groups')
    with op.batch_alter_table('collection_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_targets_period_start'))

    op.drop_table('collection_targets')
    # ### end Alembic commands ###
