import { useMemo, useState } from 'react';
import { useSelector } from 'react-redux';
import { ArrowRight, ChevronRight, CircleCheck, HandCoins, Search, ShieldCheck, UserPlus, UsersRound } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import AppShell from '../components/AppShell';

const INDIVIDUAL = 'No Chama / Individual Borrower';
const scoreLabel = (score) => score >= 75 ? 'Strong' : score >= 60 ? 'Watch' : 'At risk';

export default function Chamas() {
  const navigate = useNavigate(); const customers = useSelector((state) => state.customers.list);
  const [search, setSearch] = useState(''); const [selectedName, setSelectedName] = useState('');
  const groups = useMemo(() => Object.entries(customers.reduce((all, customer) => {
    if (customer.chama && customer.chama !== INDIVIDUAL) all[customer.chama] = [...(all[customer.chama] || []), customer];
    return all;
  }, {})).map(([name, members]) => {
    const averageScore = Math.round(members.reduce((sum, member) => sum + (member.creditScore || 0), 0) / members.length);
    return { name, members, averageScore, overdue: members.filter((member) => member.status === 'Overdue').length, chairperson: members.find((member) => member.chamaRole === 'chairperson') || members[0] };
  }), [customers]);
  const shown = groups.filter((group) => group.name.toLowerCase().includes(search.toLowerCase()));
  const selected = groups.find((group) => group.name === selectedName) || shown[0];
  const groupedMembers = groups.reduce((sum, group) => sum + group.members.length, 0);

  return <AppShell title="Chama Groups" subtitle="Manage group membership and group loan applications.">
    <section className="rounded-3xl bg-gradient-to-br from-brand-700 to-brand-500 p-5 text-white shadow-sm sm:p-7"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm text-brand-100">Community lending</p><h1 className="mt-1 font-display text-2xl font-semibold">Group loans, led by the chairperson.</h1><p className="mt-2 max-w-xl text-sm leading-6 text-brand-50">Chama loans are submitted for the whole group. Personal loans remain in the customer profile.</p></div><button type="button" onClick={() => navigate('/customers/new')} className="inline-flex w-fit items-center gap-2 rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-brand-700 hover:bg-brand-50"><UserPlus size={17} /> Add group member</button></div><div className="mt-6 grid grid-cols-3 gap-3 border-t border-white/20 pt-5"><HeroMetric label="Active Chamas" value={groups.length} /><HeroMetric label="Group members" value={groupedMembers} /><HeroMetric label="Individual traders" value={customers.length - groupedMembers} /></div></section>
    <div className="mt-6 grid gap-5 xl:grid-cols-[minmax(0,1fr)_390px]"><section><div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-display text-lg font-semibold text-slate-900">Chama groups</h2><p className="mt-1 text-sm text-slate-500">Select a group to submit or review its group loan.</p></div><label className="relative sm:w-64"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search groups..." className="w-full rounded-xl border border-brand-100 bg-white py-2.5 pl-9 pr-3 text-sm focus:outline-none focus:ring-2 focus:ring-brand-300" /></label></div><div className="grid gap-4 md:grid-cols-2">{shown.map((group) => <button type="button" key={group.name} onClick={() => setSelectedName(group.name)} className={`rounded-2xl border bg-white p-5 text-left shadow-sm transition hover:shadow-md ${selected?.name === group.name ? 'border-brand-500 ring-1 ring-brand-200' : 'border-brand-100'}`}><div className="flex items-start justify-between gap-3"><span className="grid size-11 place-items-center rounded-xl bg-brand-50 text-brand-700"><UsersRound size={21} /></span><span className="rounded-full bg-brand-50 px-2.5 py-1 text-xs font-semibold text-brand-700">{scoreLabel(group.averageScore)}</span></div><h3 className="mt-4 font-display font-semibold text-slate-900">{group.name}</h3><p className="mt-1 text-sm text-slate-500">Chairperson: {group.chairperson.name}</p><div className="mt-4 grid grid-cols-3 border-t border-brand-50 pt-4 text-center"><Metric label="Members" value={group.members.length} /><Metric label="Trust" value={group.averageScore} /><Metric label="Overdue" value={group.overdue} danger={group.overdue > 0} /></div><span className="mt-4 inline-flex items-center gap-1 text-sm font-medium text-brand-600">Open group <ChevronRight size={16} /></span></button>)}</div>{!shown.length && <div className="rounded-2xl border border-dashed border-brand-200 bg-white p-10 text-center text-sm text-slate-500">No Chama groups match your search.</div>}</section><aside className="h-fit rounded-2xl border border-brand-100 bg-white shadow-sm xl:sticky xl:top-5">{selected ? <GroupDetail group={selected} onRequest={() => navigate(`/loans?customer=${encodeURIComponent(selected.chairperson.id)}&chama=${encodeURIComponent(selected.name)}&members=${selected.members.length}&groupLoan=1`)} onCustomer={(id) => navigate(`/customers?customer=${encodeURIComponent(id)}`)} /> : <p className="p-8 text-center text-sm text-slate-500">Select a Chama to continue.</p>}</aside></div>
  </AppShell>;
}

function GroupDetail({ group, onRequest, onCustomer }) { return <><div className="border-b border-brand-100 p-5"><div className="flex gap-3"><span className="grid size-10 place-items-center rounded-xl bg-brand-50 text-brand-700"><ShieldCheck size={19} /></span><div><p className="text-xs font-medium uppercase tracking-wide text-brand-600">Chama loan</p><h2 className="mt-1 font-display text-lg font-semibold text-slate-900">{group.name}</h2></div></div><div className="mt-4 rounded-xl bg-brand-50 p-3 text-sm text-brand-800"><p className="flex items-center gap-2 font-semibold"><CircleCheck size={17} /> Chairperson: {group.chairperson.name}</p><p className="mt-1 pl-6 text-xs">The chairperson registers this loan for all {group.members.length} members.</p></div></div><div className="p-5"><button type="button" onClick={onRequest} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-brand-500 px-4 py-3 text-sm font-semibold text-white hover:bg-brand-600"><HandCoins size={17} /> Request group loan</button><p className="mt-2 text-center text-xs text-slate-500">This is a Chama group loan—not a personal loan.</p><div className="mt-5 flex items-center justify-between"><h3 className="font-display font-semibold text-slate-900">Members</h3><span className="text-sm text-slate-500">{group.members.length} total</span></div><ul className="mt-3 divide-y divide-brand-50">{group.members.map((member) => <li key={member.id} className="flex items-center gap-3 py-3"><span className="grid size-9 place-items-center rounded-full bg-brand-100 text-xs font-semibold text-brand-700">{member.name.split(' ').map((part) => part[0]).slice(0, 2).join('')}</span><button type="button" onClick={() => onCustomer(member.id)} className="min-w-0 flex-1 text-left"><p className="truncate text-sm font-medium text-slate-800">{member.name}{member.id === group.chairperson.id && <span className="ml-1 text-xs font-normal text-brand-600">(Chairperson)</span>}</p><p className="text-xs text-slate-500">Trust score: {member.creditScore || '—'}</p></button></li>)}</ul><button type="button" onClick={() => onCustomer(group.chairperson.id)} className="mt-3 inline-flex w-full items-center justify-center gap-2 py-2 text-sm font-medium text-brand-600 hover:underline">Open chairperson profile <ArrowRight size={15} /></button></div></>; }
function HeroMetric({ label, value }) { return <div><p className="font-display text-2xl font-semibold">{value}</p><p className="mt-0.5 text-xs text-brand-100">{label}</p></div>; }
function Metric({ label, value, danger }) { return <div className="border-r border-brand-50 last:border-0"><p className={`font-display text-base font-semibold ${danger ? 'text-red-600' : 'text-slate-900'}`}>{value}</p><p className="mt-0.5 text-[11px] text-slate-500">{label}</p></div>; }
