import { useState } from 'react';
import { Mail, ShieldCheck, UserPlus } from 'lucide-react';
import AppShell from '../components/AppShell';
import { addLoanOfficer, getLoanOfficers } from '../data/mockAuth';

export default function LoanOfficers() {
  const [officers, setOfficers] = useState(getLoanOfficers());
  const [form, setForm] = useState({ name: '', email: '', pin: '' }); const [error, setError] = useState('');
  function submit(e) { e.preventDefault(); setError(''); try { const officer = addLoanOfficer(form); setOfficers((all) => [...all, officer]); setForm({ name: '', email: '', pin: '' }); } catch (err) { setError(err.message); } }
  return <AppShell title="Loan Officers" subtitle="Admin-only staff provisioning">
    <div className="grid lg:grid-cols-2 gap-6"><section className="bg-white rounded-2xl border border-brand-100 p-6"><div className="flex gap-2 items-center mb-5"><UserPlus className="text-brand-600" size={20} /><h2 className="font-display font-semibold text-slate-900">Add loan officer</h2></div><form onSubmit={submit} className="space-y-4"><Input label="Full name" value={form.name} onChange={(name) => setForm({ ...form, name })} /><Input label="Email" type="email" value={form.email} onChange={(email) => setForm({ ...form, email })} /><Input label="Set PIN" type="password" value={form.pin} onChange={(pin) => setForm({ ...form, pin })} pattern="[0-9]{4,8}" /><p className="text-xs text-slate-500">The loan officer uses this email and PIN to sign in. They cannot create their own account.</p>{error && <p className="text-sm text-red-600">{error}</p>}<button className="w-full py-3 rounded-xl bg-brand-500 text-white font-medium hover:bg-brand-600">Create loan officer</button></form></section>
    <section className="bg-white rounded-2xl border border-brand-100"><div className="p-5 border-b border-brand-100"><h2 className="font-display font-semibold text-slate-900">Active loan officers ({officers.length})</h2></div>{officers.length === 0 ? <p className="p-8 text-center text-sm text-slate-400">No loan officers added yet.</p> : <div className="divide-y divide-brand-50">{officers.map((officer) => <div key={officer.id} className="p-4 flex items-center gap-3"><div className="w-9 h-9 rounded-full bg-brand-100 text-brand-700 flex items-center justify-center font-medium">{officer.name[0]}</div><div className="min-w-0 flex-1"><p className="font-medium text-slate-900">{officer.name}</p><p className="text-xs text-slate-500 flex gap-1 items-center"><Mail size={12} />{officer.email}</p></div><ShieldCheck size={18} className="text-brand-600" /></div>)}</div>}</section></div>
  </AppShell>;
}
function Input({ label, value, onChange, type = 'text', pattern }) { return <label className="block text-sm font-medium text-slate-600">{label}<input required type={type} inputMode={label === 'Set PIN' ? 'numeric' : undefined} minLength={label === 'Set PIN' ? 4 : undefined} maxLength={label === 'Set PIN' ? 8 : undefined} pattern={pattern} value={value} onChange={(e) => onChange(e.target.value)} className="mt-1.5 w-full rounded-xl border border-brand-100 px-3 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-brand-300" /></label>; }
