import { useMemo, useState } from 'react'
import { generateSchedule, money } from '../api/loansApi'

const button = 'rounded border px-3 py-2 text-sm font-bold'
export function PendingQueue({ loans, role, onApprove, onReject }) {
  const [rejecting, setRejecting] = useState(null); const [reason, setReason] = useState(''); const [notes, setNotes] = useState(''); const [conditions, setConditions] = useState({})
  const pending = loans.filter((loan) => loan.status === 'Pending')
  if (!pending.length) return <Empty label="No pending applications." />
  return <div className="grid gap-3">{pending.map((loan) => <article key={loan.id} className="rounded-lg border border-[#e9ebe5] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="m-0">{loan.customer}</h3><p className="mb-0 text-sm text-[#5c635a]">{loan.business} · KES {money(loan.amount)} · {loan.duration} months</p></div><span className="rounded bg-[#fff4ce] px-2 py-1 text-xs font-bold text-[#7a5700]">Pending</span></div>{role === 'loan_officer' || role === 'manager' ? <div className="mt-4 grid gap-2"><input className="h-10 border border-[#bdc8b6] px-3 text-sm" placeholder="Approval conditions (optional)" value={conditions[loan.id] || ''} onChange={(e) => setConditions({ ...conditions, [loan.id]: e.target.value })} /><div className="flex gap-2"><button className={`${button} border-[#397d09] bg-[#397d09] text-white`} onClick={() => onApprove(loan, conditions[loan.id])}>Approve</button><button className={`${button} border-[#bc1511] text-[#bc1511]`} onClick={() => setRejecting(loan.id)}>Reject</button></div>{rejecting === loan.id && <div className="grid gap-2 rounded bg-[#fff7f6] p-3"><select aria-label="Rejection reason" className="h-10 border border-[#bdc8b6] px-2" value={reason} onChange={(e) => setReason(e.target.value)}><option value="">Select required rejection reason</option><option>Insufficient affordability evidence</option><option>Incomplete application</option><option>Existing overdue balance</option></select><textarea className="border border-[#bdc8b6] p-2 text-sm" placeholder="Notes (optional)" value={notes} onChange={(e) => setNotes(e.target.value)} /><button disabled={!reason} className={`${button} border-[#bc1511] bg-[#bc1511] text-white disabled:opacity-40`} onClick={() => { onReject(loan, reason, notes); setRejecting(null); setReason(''); setNotes('') }}>Confirm rejection</button></div>}</div> : <p className="mb-0 mt-4 text-sm text-[#687068]">Approval actions are limited to loan officers and managers.</p>}</article>)}</div>
}
export function DisbursementQueue({ loans, onDisburse }) {
  const [form, setForm] = useState({}); const [dateFilter, setDateFilter] = useState(''); const approved = loans.filter((loan) => loan.status === 'Approved'); const history = loans.filter((loan) => loan.disbursement && (!dateFilter || loan.disbursedAt === dateFilter))
  return <div className="grid gap-6"><div className="grid gap-3">{approved.length ? approved.map((loan) => { const details = form[loan.id] || { method: 'M-Pesa', date: new Date().toISOString().slice(0, 10), reference: '' }; const ready = details.date && details.reference; return <article className="rounded-lg border border-[#e9ebe5] p-4" key={loan.id}><h3 className="m-0">{loan.customer} <span className="font-normal text-[#5c635a]">— KES {money(loan.amount)}</span></h3><div className="mt-3 grid gap-2 sm:grid-cols-3"><select aria-label="Disbursement method" className="h-10 border border-[#bdc8b6] px-2" value={details.method} onChange={(e) => setForm({ ...form, [loan.id]: { ...details, method: e.target.value } })}><option>Cash</option><option>M-Pesa</option><option>Airtel Money</option></select><input className="h-10 border border-[#bdc8b6] px-2" type="date" value={details.date} onChange={(e) => setForm({ ...form, [loan.id]: { ...details, date: e.target.value } })} /><input className="h-10 border border-[#bdc8b6] px-2" placeholder="Reference number" value={details.reference} onChange={(e) => setForm({ ...form, [loan.id]: { ...details, reference: e.target.value } })} /></div><button disabled={!ready} className={`${button} mt-3 border-[#397d09] bg-[#397d09] text-white disabled:opacity-40`} onClick={() => onDisburse(loan, details)}>Record disbursement</button></article> }) : <Empty label="No approved loans awaiting disbursement." />}</div><section><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><h3 className="m-0">Disbursement history</h3><input aria-label="Filter disbursements by date" className="h-9 border border-[#bdc8b6] px-2 text-sm" type="date" value={dateFilter} onChange={(e) => setDateFilter(e.target.value)} /></div>{history.length ? <div className="overflow-x-auto"><table className="w-full min-w-[500px] text-left text-sm"><thead className="bg-[#f5f5f7]"><tr><th className="p-2">Loan</th><th className="p-2">Date</th><th className="p-2">Method</th><th className="p-2">Reference</th></tr></thead><tbody>{history.map((loan) => <tr className="border-b border-[#eee]" key={loan.id}><td className="p-2">{loan.customer} · {loan.id}</td><td className="p-2">{loan.disbursedAt}</td><td className="p-2">{loan.disbursement.method}</td><td className="p-2">{loan.disbursement.reference}</td></tr>)}</tbody></table></div> : <p className="text-sm text-[#687068]">No disbursements for this date.</p>}</section></div>
}
export function LoanDetail({ loan, onClose }) {
  const [editing, setEditing] = useState(false); const generated = useMemo(() => loan.schedule?.length ? loan.schedule : generateSchedule(loan), [loan]); const [schedule, setSchedule] = useState(generated)
  const updateItem = (number, key, value) => setSchedule((items) => items.map((item) => item.number === number ? { ...item, [key]: key === 'amount' ? Number(value) : value } : item))
  return <section className="mt-6 rounded-lg border border-[#e9ebe5] bg-white p-5"><div className="flex items-start justify-between gap-3"><div><p className="m-0 text-sm text-[#5c635a]">Loan detail · {loan.id}</p><h2 className="mt-1 text-2xl"><a className="text-[#24262b]" href={`#customers/${loan.customerId}`}>{loan.customer}</a></h2></div><button className="border-0 bg-transparent text-xl" onClick={onClose} aria-label="Close loan detail">×</button></div><div className="mt-3 flex flex-wrap gap-2 text-xs">{['Applied', 'Approved', 'Disbursed', 'Repaying', 'Closed'].map((step) => <span key={step} className={`rounded px-2 py-1 ${loan.status.includes(step) || (step === 'Applied' && loan.appliedAt) || (step === 'Approved' && loan.approvedAt) || (step === 'Disbursed' && loan.disbursedAt) ? 'bg-[#e3f2da] text-[#337609]' : 'bg-[#eceeeb] text-[#697069]'}`}>{step}</span>)}</div><div className="mt-5 flex items-center justify-between"><h3 className="m-0">Repayment schedule</h3>{loan.status === 'Pending' && <button className="text-sm font-bold text-[#397d09]" onClick={() => setEditing(!editing)}>{editing ? 'Finish editing' : 'Edit before approval'}</button>}</div><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[440px] text-left text-sm"><thead className="bg-[#f5f5f7] text-[#555b54]"><tr><th className="p-3">#</th><th className="p-3">Due date</th><th className="p-3">Amount</th><th className="p-3">Status</th></tr></thead><tbody>{schedule.map((item) => <tr className="border-b border-[#eee]" key={item.number}><td className="p-3">{item.number}</td><td className="p-3">{editing ? <input className="border p-1" type="date" value={item.dueDate} onChange={(e) => updateItem(item.number, 'dueDate', e.target.value)} /> : item.dueDate}</td><td className="p-3">{editing ? <input className="w-24 border p-1" type="number" min="0" value={item.amount} onChange={(e) => updateItem(item.number, 'amount', e.target.value)} /> : `KES ${money(item.amount)}`}</td><td className="p-3"><span className={`rounded px-2 py-1 text-xs ${item.status === 'Overdue' ? 'bg-[#ffe0df] text-[#bc1511]' : item.status === 'Paid' ? 'bg-[#e3f2da] text-[#337609]' : 'bg-[#eceeeb]'}`}>{item.status}</span></td></tr>)}</tbody></table></div>{editing && <p className="mt-3 text-sm text-[#687068]">Changes are preview-only and are locked as soon as the application is approved.</p>}</section>
}
function Empty({ label }) { return <div className="rounded-lg border border-dashed border-[#bdc8b6] p-8 text-center text-[#687068]">{label}</div> }
