import { useNavigate } from 'react-router-dom';
import Avatar from './Avatar';
import { Icon } from './Icon';

const Payment = ({ title, time, amount, balance, incoming = false }) => <div className="payment"><span className={`payment-icon ${incoming ? 'outgoing' : ''}`}>{incoming ? '↑' : '↓'}</span><div><strong>{title}</strong><small>{time}</small></div><div className={`payment-amount ${incoming ? 'negative' : ''}`}><strong>{amount}</strong><small>{balance}</small></div></div>;

export default function CustomerProfile({ customer }) {
  const navigate = useNavigate();
  return <section className="profile-area"><article className="profile-card"><div className="profile-main"><Avatar customer={customer} large /><div><h2>{customer.name}</h2><p>{customer.business}</p></div></div><div className="profile-actions"><a href="tel:+254700000000" aria-label={`Call ${customer.name}`}><Icon name="phone" /></a><button type="button" className="issue" onClick={() => navigate(`/loans?customer=${encodeURIComponent(customer.id)}`)}>Issue Loan</button></div><div className="profile-stats"><div><small>CLIENT ID</small><strong>{customer.id}</strong></div><div><small>JOINED</small><strong>Mar 12, 2021</strong></div><div><small>TOTAL LOANS</small><strong>14</strong></div><div><small>DEFAULT RATE</small><strong className="green">0%</strong></div></div></article><div className="metrics-grid"><article className="score-card"><div className="card-heading"><h2>Credit Trust Score</h2><Icon name="chart" /></div><div className="score-ring"><div><strong>85</strong><span>EXCELLENT</span></div></div><div className="score-legend"><span>Poor</span><span>Fair</span><span>Good</span><b>Excellent</b></div></article><article className="location-card"><div className="card-heading"><h2>Business Location</h2><Icon name="map" /></div><strong>Stall #42, {customer.market}</strong><p>Pumwani Rd, Nairobi</p><div className="map"><span><Icon name="pin" size={23} /></span></div></article></div><article className="payments"><div className="card-heading"><h2>Payment History</h2><button type="button" onClick={() => navigate(`/analytics?customer=${encodeURIComponent(customer.id)}`)}>View All</button></div><Payment title="Repayment - Daily Installment" time="Today, 09:45 AM · M-Pesa" amount="+ KES 500" balance="Loan Bal: KES 4,500" /><Payment title="Repayment - Daily Installment" time="Yesterday, 14:20 PM · Cash (Agent)" amount="+ KES 500" balance="Loan Bal: KES 5,000" /><Payment incoming title="Loan Disbursement - 14 Day Stock" time="Oct 24, 2023 · Bank Transfer" amount="− KES 10,000" balance="Principal Amount" /></article></section>;
}
